### ISSUE TITLE
Could you add some functions?

### ISSUE THREAD

**Issue by giwhub** [Metalnem/send-to-aria2#1]
Could you add some functions like this extension:
http://chrome.google.com/webstore/detail/aria2c-integration/edcakfpjaobkpdfpicldlccdffkhpbfk ?

**Comment by Metalnem** [comment]
Please be more specific.

**Comment by giwhub** [comment]
Like showing the speeds,controlling the actions and status of downloads?

**Comment by Metalnem** [comment]
I agree that those features would be really nice, but will not be implemented in this extension. This extension was designed to be really simple, and do just one job, which is sending downloads to aria2 server.
